version: '3.8'

services:

  oracle:
    image: gvenzl/oracle-xe:21     
    container_name: oracledatabase  
    volumes:      
      - ./oracle-volume:/home/moises/oracle/oradata
    ports:    
      - 1521:1521
    environment:      
      ORACLE_PASSWORD : root
      ORACLE_DATABASE : test
      APP_USER: dbuser
      APP_USER_PASSWORD: dbuser

volumes: 
   oracle-volume:
